export const FETCH_DATA = "FETCH_DATA";
export const CREATE_PRODUCT = "CREATE_PRODUCT";

export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const UPDATE_USER = "UPDATE_USER";

export const SETUP_USER = "SETUP_USER";

export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const CHANGE_PRODUCT_AMOUNT = "CHANGE_PRODUCT_AMOUNT";
